version: '3.7'

networks:
  rib-overlay-network:
    external: true

services:
  pixelfed-redis:
    container_name: pixelfed-redis
    image: redis:6.0.6
    labels:
      race.rib.deployment-name: ${DEPLOYMENT_NAME}
    networks:
    - rib-overlay-network

  pixelfed-redis-whiteboard:
    command: -w 8
    container_name: pixelfed-redis-whiteboard
    depends_on:
    - pixelfed-redis
    hostname: race.example2
    image: ghcr.io/tst-race/race-core/twosix-whiteboard:main
    labels:
      race.rib.deployment-name: ${DEPLOYMENT_NAME}
    networks:
    - rib-overlay-network
    environment:
    - REDIS_HOSTNAME=pixelfed-redis
x-logging:
  driver: json-file
  options:
    max-file: '5'
    max-size: 1m

