name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - '2.6.0'
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Prepare
        run: |
          ./prepare_artifacts_pixelfed.sh
          ./prepare_artifacts_avideo.sh
          ./prepare_artifacts_dash.sh

      - name: Create Build Artifact
        run: |
          echo LOCALE $(ls -ltrah)
          echo WHICH $(which tar)
          tar cvf race-destini-pixelfed.tar.gz -C pixelfed-plugin .
          tar cvf race-destini-avideo.tar.gz -C avideo-plugin .
          tar cvf race-destini-dash.tar.gz -C dash-plugin .

      - name: Upload Pixelfed Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "race-destini-pixelfed.tar.gz"
          path: "race-destini-pixelfed.tar.gz"
          retention-days: 10

      - name: Upload Avideo Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "race-destini-avideo.tar.gz"
          path: "race-destini-avideo.tar.gz"
          retention-days: 10

      - name: Upload Dash Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "race-destini-dash.tar.gz"
          path: "race-destini-dash.tar.gz"
          retention-days: 10

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            race-destini-pixelfed.tar.gz
            race-destini-avideo.tar.gz
            race-destini-dash.tar.gz
